services:
  postgresql:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: bob
      POSTGRES_USER: bob
      POSTGRES_DB: smartbarbo
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/18/docker

volumes:
  postgresql_data: