services:
  postgresql:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: bob
      POSTGRES_USER: bob
      POSTGRES_DB: smartbarbo
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/18/docker
  postgresql-keycloak:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: kc
      POSTGRES_USER: kc
      POSTGRES_DB: kc
    ports:
      - '5433:5432'
    volumes:
      - postgresql-keycloak_data:/var/lib/postgresql/18/docker
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql-keycloak:5432/kc
      KC_DB_USERNAME: kc
      KC_DB_PASSWORD: kc
    ports:
      - '7070:8080'
    depends_on:
      - postgresql-keycloak
    volumes:
      - ./docker/keycloak/realm:/opt/keycloak/data/import
    command: [ "start-dev", "--import-realm" ]
  redis:
    image: redis:8.10.0
    ports:
      - '6379:6379'
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - '5540:5540'
  mongo:
    image: mongo:8
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - "18081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      mongo:
        condition: service_started

volumes:
  postgresql_data:
  postgresql-keycloak_data:
  mongo_data:
