quarkus:
  datasource:
    username: bob
    password: bob
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/smartbarbo
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
  http:
    ssl:
      certificate:
        key-store-file: smartbarbo.p12
        trust-store-file: sbotrust.p12
      client-auth: required
    insecure-requests: redirect

smartbar.backoffice.foo: baz