quarkus:
  datasource:
    username: bob
    password: bob
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/smartbarbo
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
  http:
    auth:
      form:
        enabled: true
        login-page: loginSPA.html
        error-page: ""
        landing-page: ""

smartbar.backoffice.foo: baz