quarkus:
  datasource:
    username: bob
    password: bob
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/smartbarbo
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
  # http:
  #   ssl:
  #     certificate:
  #       key-store-password: ""
  #       trust-store-password: ""
  #     client-auth: required
  #   insecure-requests: redirect
  oidc:
    auth-server-url: http://localhost:7070/realms/sbo
    client-id: smartbar-backoffice
    credentials:
      secret: ""
    application-type: hybrid
    token-state-manager:
      split-tokens: true
    roles:
      source: accesstoken
  kafka:
    devservices:
      enabled: false
    bootstrap:
      servers: localhost:9092
  rabbitmq:
    devservices:
      enabled: false
  messaging:
    outgoing:
      menu-update-events:
        connector: smallrye-rabbitmq
        default-routing-key: menuupdates
        exchange:
          type: direct
          name: smartbar

rabbitmq-host: localhost
rabbitmq-port: 5672
rabbitmq-username: ""
rabbitmq-password: ""

smartbar.backoffice.foo: baz
