quarkus:
  http:
    port: 8081
  management:
    port: 9001
  rest-client:
    de.schulte.smartbar.orderclient.login.MenuApiClient:
      url: ""
  cache:
    redis:
      expire-after-write: 60S
      menu-cache:
        key-type: java.lang.String
        value-type: de.schulte.smartbar.orderclient.api.model.LoginResponseBody
