quarkus:
  http:
    port: 8081
  management:
    port: 9001
  rest-client:
    de.schulte.smartbar.orderclient.login.MenuApiClient:
      url: ""
  cache:
    caffeine:
      expire-after-write: PT1M
  redis:
    hosts: redis://localhost:6379/0
    devservices:
      enabled: false
  mongodb:
    connection-string: mongodb://localhost:27017
