quarkus:
  http:
    port: 8081
  management:
    port: 9001
  rest-client:
    de.schulte.smartbar.orderclient.login.MenuApiClient:
      url: ""
  cache:
    caffeine:
      expire-after-write: PT2S
